### ISSUE TITLE
Foldmethod when diffing

### ISSUE THREAD

**Issue by lervag** [ludovicchabant/vim-lawrencium#10]
I'm wondering why you are setting the foldmethod to marker for the `Hgrecord` buffers (i.e. in `s:HgRecord`). Should it not be set to diff mode instead?

**Comment by lervag** [comment]
I'm also using the `FastFold` method for folding, which sets the `w:lastfdm` variable and keeps the foldmethod on manual to speed up folding. I understand it might be too much to ask, but I would be very happy if it was possible to support this and to preserve the `w:lastfdm` variable.

**Comment by ludovicchabant** [comment]
The first comment is correct, I believe. I updated the code accordingly with 9f74adedd9793d4d08277845a5713eff38790579.

About the second thing, I'm not convinced, though. I wouldn't want to do something using `FastFold`'s internals, only for it to not work anymore if the authors refactor something. What happens exactly right now?

**Comment by lervag** [comment]
1. Thanks!
2. I'll investigate some more and get back to you.

**Comment by lervag** [comment]
The second part is now fixed through https://github.com/Konfekt/FastFold/issues/35.
