### ISSUE TITLE
v:errmsg pollution on startup outside of mercurial repository

### ISSUE THREAD

**Issue by hardenedapple** [ludovicchabant/vim-lawrencium#13]
The `lawrencium#throw()` function sets `v:errmsg` before `throw`ing its argument.
This means that in `lawrencium#setup_buffer_commands()` the `try/catch` block to check whether there is a mercurial repository around sets `v:errmsg` despite not actually being in error.

It's not much of a problem, but I thought I'd mention it.

**Comment by ludovicchabant** [comment]
Hi!
I don't really understand what you mean... are you talking about the try/catch block [over here](https://github.com/ludovicchabant/vim-lawrencium/blob/master/autoload/lawrencium.vim#L635) ?
How does `v:errmsg` ends up being set?

**Comment by hardenedapple** [comment]
Hi there.

Yeah, that's the block I mean.

When you start vim outside of a mercurial repo, lawrencium#hg_repo() calls lawrencium#find_repo_root() and that function calls lawrencium#throw() because it can't find a mercurial repo.

lawrencium#throw() sets v:errmsg.

**Comment by ludovicchabant** [comment]
Should be fixed with 7a39532a617af3f20bcf4e9992c0a423b30932ae! Thanks.

**Comment by ludovicchabant** [comment]
Should be fixed with a8732104ddd5d1f778943d09cf09de7bfb4cfb26, thanks!
