### ISSUE TITLE
Extension does not work when using Hg share

### ISSUE THREAD

**Issue by simonbz** [ludovicchabant/vim-lawrencium#14]
It looks like the extension does not work when creating a shared repository.  While digging in the plugin, I found out that we're relying on a '.hg/store' directory that does not exist on a shared repository.  The following diff fixed the issue for me.

```
     while l:path != l:previous_path
         if isdirectory(l:path . '/.hg/store')
             return s:normalizepath(simplify(fnamemodify(l:path, ':p')))
+        elseif filereadable(l:path . '/.hg/sharedpath')
+            return s:normalizepath(simplify(fnamemodify(l:path, ':p')))
         endif
         let l:previous_path = l:path
         let l:path = fnamemodify(l:path, ':h')
```

**Comment by ludovicchabant** [comment]
Even though I'm responding to this 4 years late, it looks like this code was changed 6 years ago to check for just a `.hg` directory anyway, which should cover both cases. See 44969e708a29224c67be64a26a2cac8da1ac670f
