### ISSUE TITLE
/bin/bash hg command not found

### ISSUE THREAD

**Issue by jimgreen** [ludovicchabant/vim-lawrencium#15]
Dear lawrencium community,

My cluster does not have Hg, thus I compiled my own and use it through alias like

alias hg="PATH-TO-MY-HG-BUILD"

Can lawrencium pick up the alias?

**Comment by ludovicchabant** [comment]
Hi!

Yep, check out `g:lawrencium_hg_executable`. It defaults to `hg` so I assume it would "just work"... but in case Vim isn't running it through whatever shell you're using that defines the alias (Bash, Zsh, etc.), then you can set that variable to the direct path of the executable in you `.vimrc`.
