### ISSUE TITLE
Using hgannotatelog as a generic command outside Annotate Window

### ISSUE THREAD

**Issue by halilakin** [ludovicchabant/vim-lawrencium#16]
I use hgannotatelog a lot, but we need to open Annotate Window first and then find the line and run that command. Does it make sense to allow running that command outside Annotate Window too?

**Comment by ludovicchabant** [comment]
Hi! Yeah it does make sense -- it would require implementing a new command, however, which looks up the the current line in a hidden `annotate` buffer and then figures out the revision to `log`.

**Comment by ludovicchabant** [comment]
I recently needed this feature so after all these years I decided to implement it! See a790513b278eba1279e1f053aab760cbddbc3872
