### ISSUE TITLE
Use of `HGPLAIN` breaks aliases when invoking `:Hg`

### ISSUE THREAD

**Issue by 0jrp0** [ludovicchabant/vim-lawrencium#20]
`lawrencium#hg#Hg` invokes `repo.RunCommandEx` which sets `HGPLAIN` to guarantee certain behaviors when invoking and processing mercurial commands. However, this breaks legitimate aliases which might be invoked from `:Hg`.

Also, the restoration attempt of `HGPLAIN` is also not correct. Mercurial looks at the existence of the variable in the environment to set plain mode. You could put `HGPLAIN=0` / `HGPLAIN='false'` and it would still behave the same as `HGPLAIN='true'`. So restoring the `l:prev_hgplain` is a noop. At best, you would have to use the [unlet-$](https://vimhelp.org/eval.txt.html#%3Aunlet-%24) command to expunge it from the environment.

Proposal:

1. Don't use `HGPLAIN` for any invocation sourced from `lawrencium#hg#Hg`.
2. Use `HGPLAIN` for other invocations where output is expected to be consistent with stock Mercurial.
3. When using `HGPLAIN`, just pass it into `system()` as a prefix to the shell command. Don't attempt to restore it. Don't attempt to set it in code.

**Comment by ludovicchabant** [comment]
Hi!

Yep, points 1 and 2 are good and valid. Sorry about the bug.

Point 3 isn't portable to Windows however, so I think we have to do the `unlet-$` thing.

**Comment by ludovicchabant** [comment]
See eee52c9da9a58c1f079adb4a3134a0620bc6e945 which hopefully fixes the problem.
