### ISSUE TITLE
Expand paths in :Hg commands

### ISSUE THREAD

**Issue by flwyd** [ludovicchabant/vim-lawrencium#22]
I would like at least one of the following commands to run `hg add` on the file in the current buffer:
* `:Hg add %` (expand % into the filename in an arbitrary command, analogous the way that `:sp %` works)
* `:Hgadd` (new command for `hg add`, default to current buffer or add any arguments)

`:Hg add %` currently shows a `%: No such file or directory` error and `Hgadd` is not yet a command.

It would be tempting to call `expand()` on all arguments after `Hg` subcommands (this would allow, for example, `:Hg add %:h:h` from `foo/bar/baz/qux.txt` to run `hg add foo/bar`).  However, there might be non-file arguments to Mercurial which should not be `expand()`ed, so some care might be needed in the implementation.  Expanding arguments of specific commands like `Hgadd` and `Hgforget` might be safer.  The interaction between `lawrencium_auto_cd` and `expand()` might also need some care.

**Comment by ludovicchabant** [comment]
FWIW I implemented `%` _autocomplete_ in abbcdb51f36276b9ac90db894f79e177200cddc7 -- that is, if you spend the time to hit `<Tab>`, it will expand that argument. If not, it will pass it as is to Mercurial... which I think avoids having to be careful about things.
