### ISSUE TITLE
Ctrl-S map in status buffer not working

### ISSUE THREAD

**Issue by raddevon** [ludovicchabant/vim-lawrencium#6]
Love the plugin. Thank you for building it!

I'm having trouble getting the <C-S> keymap to work in the status buffer. I run :`Hgstatus` to bring up the buffer, set up my commit, and press Ctrl-S, but nothing seems to happen. I can manually run `:Hgstatuscommit` and it works. I can run `:map` and see that the key appears to be mapped.

I'm running OSX 10.10.2 with Vim 7.4 running inside iTerm2 build 2.0.0.20141103, in the event any of that matters.

I'm pretty new to Vim, so I may be missing some debugging step that could have fixed this. Would love any suggestions you have. Keep up the good work!

**Comment by raddevon** [comment]
I found out my shell was intercepting Ctrl-S before it got to Vim. I used [a technique from the Vim Wikia](http://vim.wikia.com/wiki/Map_Ctrl-S_to_save_current_or_new_files) to prevent this.

I added this to my .zshrc:

    alias vim="stty stop '' -ixoff ; vim"
    ttyctl -f

**Comment by ludovicchabant** [comment]
Ah yes, I also realized that recently, when `<C-S>` would completely freeze my SSH bash session on my server... wished I'd known about that when I came up with the default mappings! :(
